Remove flatpak permission "xdg-config/git"
It is not needed since we already have --filesystem=host
and it triggers a manifest linter error with Flathub

Error: 'finish-args-unnecessary-xdg-config-git-rw-access' error found in
linter manifest check.

https://docs.flathub.org/docs/for-app-authors/linter#finish-args-arbitrary-xdg-config-mode-access

https://github.com/flathub-infra/vorarbeiter/actions/runs/18469952208/job/52621104370